# Generated by Django 6.0.2 on 2026-05-13 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposition', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.IntegerField(verbose_name='День тижня (0-6)')),
                ('is_working', models.BooleanField(default=True, verbose_name='Чи робочий?')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time_slot', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='my_bot.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(verbose_name='Година (0-23)')),
                ('working_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='my_bot.workingday')),
            ],
        ),
    ]
