# Generated by Django 6.0.2 on 2026-05-13 20:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghour',
            name='hour',
        ),
        migrations.AddField(
            model_name='workinghour',
            name='hour_end_work',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Кінець (0-23)'),
        ),
        migrations.AddField(
            model_name='workinghour',
            name='hour_start_work',
            field=models.IntegerField(default=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Початок (0-23)'),
        ),
        migrations.AddField(
            model_name='workinghour',
            name='interval',
            field=models.IntegerField(choices=[(10, '10 хв'), (15, '15 хв'), (20, '20 хв'), (30, '30 хв'), (45, '45 хв'), (60, '60 хв')], default=60, verbose_name='Інтервал'),
        ),
        migrations.AlterField(
            model_name='work',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступно'),
        ),
        migrations.AlterField(
            model_name='work',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='work',
            name='proposition',
            field=models.CharField(max_length=100, verbose_name='Назва послуги'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='day_index',
            field=models.IntegerField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, 'П’ятниця'), (5, 'Субота'), (6, 'Неділя')], unique=True, verbose_name='День тижня (0-6)'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='working_day',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='my_bot.workingday'),
        ),
    ]
